drivers: touchscreen: mxs-ts: allow driver to be built as module
Since the mxs-ts driver doesn't specify a license, some api's
are not available when the driver is built as a module.  This
results in the following error at module load time:

mxs_ts: module license 'unspecified' taints kernel.
Disabling lock debugging due to kernel taint
mxs_ts: Unknown symbol platform_driver_unregister (err 0)
mxs_ts: Unknown symbol platform_driver_register (err 0)
mxs_ts: Unknown symbol platform_get_resource (err 0)
ERROR: could not insert 'mxs_ts': Unknown symbol in module, or unknown parameter
 (see dmesg)

This patch adds the proper GPL license field.

Signed-off-by: Steve Sakoman <steve@sakoman.com>